### ISSUE TITLE
Some free games don't work

### ISSUE THREAD

**Issue by AstraC1** [SteamTimeIdler/stidler#11]
All of Yu-Gi-Oh duel links, Warframe, toribash, and bloons TD battles don't work.

**Comment by SteamTimeIdler** [comment]
Hi

If you check the game ids match what they are in Steam you will know.

Some games have duplicates in the game's list. I don't know why, that's one for Steam to answer as it all derives from their official games list.

Simply select the other one in the games list if there are multiples and it will work fine

ALSO: Make sure the games appear in your library or it won't register on your account

Hope that helps!

Ti
