### ISSUE TITLE
Getting shared secret from new app

### ISSUE THREAD

**Issue by ddavef** [SteamTimeIdler/stidler#16]
Hi,

Recently Valve updated their steam app and the location for the shared secret is no longer at `/data/data/com.valvesoftware.android.steam.community/f/Steamguard-STEAMID64`

Does anyone know where to find the shared secret with the new app?

**Comment by Committing** [comment]
You haven't been able to capture the shared_secret on mobiles for over 4 years.

See https://steamtimeidler.com/shared_secret for info on how to get your shared_secret with other authentication methods.

**Comment by ddavef** [comment]
Well, time really does fly. Thanks for your response, I will now close this issue.
