### ISSUE TITLE
Add 2FAS as an option to continue receiving your 2FA code on your phone

### ISSUE THREAD

**Issue by ait-artem-stankov** [SteamTimeIdler/stidler#18]
You can now also use 2FAS to continue receiving your 2factor authentication code on your phone - https://2fas.com/support/2fas-mobile-app/how-to-add-a-steam-guard-token/. 
@SteamTimeIdler please add this to the wiki page

**Comment by Committing** [comment]
Hi @art-stankov, thanks I've updated the wiki 🥇

**Comment by ait-artem-stankov** [comment]
Thanks for the quick action
