### ISSUE TITLE
Stidler/steamtimeidler shows hours gained but it isn't showing on Steam

### ISSUE THREAD

**Issue by HeckFin52** [SteamTimeIdler/stidler#2]
Stidler show I gained 400+hours but I didn't see the time changed on the steam profile, using mobile auth,offline mode

**Comment by SteamTimeIdler** [comment]
Hi HeckFin

Sometimes Steam can be slow to update. Leave it a bit longer and you will start to see the hours rack in.

As long as the icon shows as green and not red then you are idling.

Cheers

Ti Rone
[stidler.com](http://stidler.com)

**Comment by HeckFin52** [comment]
Actually,it never updates. did i do anything wrong?

SteamTimeIdler notifications@github.com于2016年10月21日周五 下午4:20写道：

**Comment by SteamTimeIdler** [comment]
1. Make sure the icon is green on your control panel
2. Make sure you have added the games to your config
3. You must have the game in your library to gain hours on it. You don't need it installed however.
