### ISSUE TITLE
Say's the wrong gained time

### ISSUE THREAD

**Issue by Nizzl1337** [SteamTimeIdler/stidler#3]
I haven't even had it for 24 hours and it already says it has gained 60 hours

it only got 20 hours since i had 40 hours and now 60

http://prntscr.com/d9ct4s

**Comment by SteamTimeIdler** [comment]
Hi

What is your SteamTimeIdler username?

Cheers

**Comment by Nizzl1337** [comment]
Nizzl

**Comment by SteamTimeIdler** [comment]
Please try clicking 'Force stop idle' button to reset your idle sessions and restart your idle.

This should sort the issue.

Our idles are currently being recoded entirely for a new site soon.

**Comment by Nizzl1337** [comment]
Alright thanks anyway.

**Comment by SteamTimeIdler** [comment]
You were still on an old server. This forced your account onto the new server rectifying the issue.

Cheers
