### ISSUE TITLE
family sharing hours not counting 

### ISSUE THREAD

**Issue by woodsy2000** [SteamTimeIdler/stidler#4]
when i family share it seems that the hours don't count for the games that ive idled on and it just stays at 0 is that normal?

**Comment by SteamTimeIdler** [comment]
Hi, [SteamTimeIdler](http://stidler.com) can only idle on games that show in your library. If it does not show in your library then you are unable to idle on it.

So yes you can idle on family shared games.

This means you are **not required** to download your game in order to idle on it.

Cheers

**Comment by woodsy2000** [comment]
alright just wondering ;D

**Comment by SteamTimeIdler** [comment]
Happy idling!
