### ISSUE TITLE
Auto-Restarter is not working for me

### ISSUE THREAD

**Issue by mathas5** [SteamTimeIdler/stidler#9]
Hello! So I have this issue and I don't know how to fix it. I really want to use Auto-Restarter, but when I paste my shared_secret code, error 88 popping out. I'm pasting my shared_secret code with all quotes ( "shared_secret":"#############################" ) and error 88 still popping out. I'm pretty sure that is my correct shared_secret code. Thanks for reading!

P.S Sorry for my bad english skills, I tried my best.

**Comment by SteamTimeIdler** [comment]
Hi Mathas

Thanks for getting in contact.

Error 88 is an error that means your Mobile idle has been interrupted by an  outside source. 

Generally error 88 means Steam has gone down for updates. This happens most often at the beginning of each week. This does not affect email auth users as they can reconnect again automatically without requiring a new code.

If you believe you have your shared_secret code in but it isn't auto-restarting when Steam goes down then it's most probable that your code in input incorrectly or you have the wrong code.

When you enter the shared_secret code make sure you only enter what is between the quotes:

( "shared_secret":"**#############################**" )

Only input the code that I have made bold. When you start your idle also input your usual mobile auth code. Then let your idle run for 30 minutes so you know you are in the auto-restarter queue and you should be sorted.

We plan some major restructuring of how this works in the future on our new website.

Cheers

**Comment by mathas5** [comment]
Hello again!

Now I understand what I did wrong. I entered the code incorrectly. Everything is working perfect right now.

Thanks for your support,

Mathas
